"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.isActive = exports.getColumnName = exports.getProjectName = void 0;
const core_1 = require("@actions/core");
const github_action_helper_1 = require("@technote-space/github-action-helper");
const getProjectName = () => (0, core_1.getInput)('PROJECT', { required: true });
exports.getProjectName = getProjectName;
const getColumnName = () => (0, core_1.getInput)('COLUMN', { required: true });
exports.getColumnName = getColumnName;
const isActive = (target) => github_action_helper_1.Utils.getBoolValue((0, core_1.getInput)(`CHECK_${target}_PROJECT`));
exports.isActive = isActive;
